# Generated by Django 4.0.4 on 2023-01-29 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("less_users", "0002_userchallenge_log"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userchallenge",
            options={"ordering": ["-is_active"]},
        ),
        migrations.AddField(
            model_name="userchallenge",
            name="is_deleted",
            field=models.BooleanField(
                default=False, help_text="visible or not in my_challenges list"
            ),
        ),
    ]
