# Generated by Django 4.0.4 on 2022-06-27 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Challenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "duration",
                    models.IntegerField(
                        help_text="how long it takes to complete challenge"
                    ),
                ),
                (
                    "frequency",
                    models.IntegerField(
                        help_text="how often challenge is activated: "
                        "1/day, 1/week, 1/month, 1/year"
                    ),
                ),
                (
                    "points",
                    models.IntegerField(
                        help_text="how many points are gained "
                        "each time challenge is completed"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CategoryChallenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="challenges.category",
                    ),
                ),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="challenges.challenge",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Challenges categories",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="challenges",
            field=models.ManyToManyField(
                through="challenges.CategoryChallenge", to="challenges.challenge"
            ),
        ),
    ]
